version: '3.5'
services:
  plex:
    network_mode: host
    image: plexinc/pms-docker
    env_file:
      - .env.plex
    volumes:
      - .docker/data/plex/config:/config
      - .docker/data/plex/transcode:/transcode
      - /home:/data
    logging:
      driver: gelf
      options:
        tag: plex
        gelf-address: udp://localhost:12201
  transmission:
    image: linuxserver/transmission:latest
    restart: unless-stopped
    ports:
      - 8112:9091
      - 51413:51413/udp
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "Europe/Warsaw"
    volumes:
      - .docker/data/transmission:/config
      - /home/pjw:/data
      - /home/pjw/tmp:/downloads_incomplete
      - /home/pjw/tv:/downloads
    logging:
      driver: gelf
      options:
        tag: transmission
        gelf-address: udp://localhost:12201
  flexget:
    image: cpoppema/docker-flexget
    network_mode: host
    environment:
      PGID: 1000
      PUID: 1000
      TZ: "Europe/Warsaw"
      WEB_PASSWD: myhorriblesecret
      TORRENT_PLUGIN: transmission
    restart: unless-stopped
    volumes:
      - .docker/data/flexget:/config
      - /home/pjw/tv:/downloads
    logging:
      driver: gelf
      options:
        tag: flexget
        gelf-address: udp://localhost:12201
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
      - "28016:28016"
    volumes:
      - ".docker/data/minecraft:/data"
    environment:
      PGID: 1000
      PUID: 1000
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "testing"
      RCON_PORT: 28016
      REPLACE_ENV_VARIABLES: "TRUE"
      VERSION: "1.12.2"
      TYPE: "forge"
      FORGEVERSION: "14.23.5.2768"
      ENV_VARIABLE_PREFIX: "MCFG_"
      SERVER_NAME: "Adloquium"
    logging:
      driver: gelf
      options:
        tag: minecraft
        gelf-address: udp://localhost:12201
    restart: always
  rcon:
    image: itzg/rcon
    environment:
      PGID: 1000
      PUID: 1000
    ports:
      - "4326:4326"
      - "4327:4327"
    links:
      - minecraft
    volumes:
      - ".docker/data/rcon:/opt/rcon-web-admin/db"
