# Supporting services, like database that always must be online
version: '3.5'
services:
  redis:
    image: redis:4.0.10
    ports:
      - 6379:6379
    volumes:
      - .docker/data/redis:/data
    logging:
      driver: gelf
      options:
        tag: redis
        gelf-address: udp://localhost:12201
  influxdb:
    restart: unless-stopped
    image: influxdb:latest
    ports:
      - "0.0.0.0:18086:8086"
    volumes:
      - .docker/data/influxdb:/var/lib/influxdb
    env_file:
      - '.env.influxdb'
    logging:
      driver: gelf
      options:
        tag: influxdb
        gelf-address: udp://localhost:12201
  grafana:
    image: grafana/grafana:5.4.2
    restart: unless-stopped
    env_file:
      - '.env.grafana'
      - '.env.influxdb'
    environment:
      GF_SERVER_DOMAIN: "${HA_DOMAIN}"
      GF_SERVER_ROOT_URL: "https://${HA_DOMAIN}/grafana/"
    ports:
      - "127.0.0.1:4100:3000"
    volumes:
      - .docker/data/grafana:/var/lib/grafana
    depends_on:
      - influxdb
    logging:
      driver: gelf
      options:
        tag: grafana
        gelf-address: udp://localhost:12201
  database:
    image: postgres:9.6.10-alpine
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    ports:
      - 0.0.0.0:5432:5432
    environment:
      PGDATA: /data
    env_file:
      - '.env.postgresql'
    volumes:
      - ./postgresql/:/docker-entrypoint-initdb.d/
      - .docker/data/postgresql:/data
      - /tmp/shared:/shared
    logging:
      driver: gelf
      options:
        tag: database
        gelf-address: udp://localhost:12201
  glances:
    restart: unless-stopped
    image: nicolargo/glances
    environment:
      - GLANCES_OPT=-w
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./glances/:/glances/conf/
    ports:
      - 7001:61208
    logging:
      driver: gelf
      options:
        tag: glances
        gelf-address: udp://localhost:12201
  rss:
    image: miniflux/miniflux:latest
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 7002:8080
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/miniflux?sslmode=disable
    env_file:
      - '.env.rss'
    logging:
      driver: gelf
      options:
        tag: rss
        gelf-address: udp://localhost:12201
  busix:
    image: macbury/busix:latest
    network_mode: host
    env_file:
      - '.env.busix'
    logging:
      driver: gelf
      options:
        tag: busix
        gelf-address: udp://localhost:12201
