title: Home
views:
  - cards:
      - entities:
          - light.hue_ambiance_lamp_1
          - light.hue_ambiance_lamp_3
        show_header_toggle: true
        title: Salon
        type: entities
      - entities:
          - light.hue_go_1
          - light.hue_ambiance_lamp_2
        show_header_toggle: true
        title: Sypialnia
        type: entities
      - entity: media_player.playstation_4
        type: media-control
      - entity: media_player.purgatory
        type: media-control
      - entity: weather.dom
        type: weather-forecast
      - entities:
        - entity: fan.xiaomi_miio_device
        - entity: input_select.xiaomi_airpurifier_mode
        - entity: input_number.xiaomi_airpurifier_favorite_level
        - entity: switch.xiaomi_airpurifier_child_lock
        - entity: switch.xiaomi_airpurifier_led
        - entity: switch.xiaomi_airpurifier_buzzer
        - entity: sensor.xiaomi_airpurifier_speed
        - entity: sensor.xiaomi_airpurifier_filter_remaining
        show_header_toggle: false
        theme: default
        title: Air Purifier
        type: entities
      - entities:
          - entity: sensor.xiaomi_airpurifier_air_quality_pm25
          - entity: sensor.xiaomi_airpurifier_temp
          - entity: sensor.xiaomi_airpurifier_humidity
        show_header_toggle: false
        theme: default
        title: Environment
        type: entities
      - entities:
          - sensor.xiaomi_airpurifier_air_quality_pm25
        hours_to_show: 80
        refresh_interval: 60
        title: Air quality
        type: history-graph

    badges:
      - person.pawel
      - person.magda
      - sun.sun
      - media_player.purgatory
      - sensor.plex
      - fan.xiaomi_miio_device
    path: default_view
    title: Home
