resources:
  - url: /local/custom-lovelace/transit/card.js?v=9
    type: module
  - url: /local/custom-lovelace/monster-card/monster-card.js?v=001
    type: module
  - url: /local/custom.css
    type: css

title: Home
background: var(--background-image)
views: !include_dir_merge_list ui/
