- hosts: adloquium
  become: yes
  roles:
    - role: weareinteractive.ufw
  vars:
    ufw_logging: "off"
    ufw_rules:
      - { port: 22, rule: allow, comment: 'Allow SSH' }
      - { port: 80, rule: allow, comment: 'Allow HTTP' }
      - { port: 1514, rule: allow, comment: 'Allow SysLog UDP' }
      - { port: 443, rule: allow, comment: 'Allow HTTPS' }
      - { port: 987, rule: allow, comment: 'Allow PS4' }
      - { port: 997, rule: allow, comment: 'Allow PS4' }
      - { port: 137, rule: allow, comment: 'Samba' }
      - { port: 138, rule: allow, comment: 'Samba' }
      - { port: 139, rule: allow, comment: 'Samba' }
      - { port: 445, rule: allow, comment: 'Samba' }
      - { from_ip: '127.0.0.1/24', comment: 'Allow localhost' }
      - { from_ip: '192.168.0.0/16', comment: 'Allow local network' }
      - { port: 32400, rule: allow, comment: 'Plex companion' }
      - { port: 3005, rule: allow, comment: 'Plex companion' }
      - { port: 5353, rule: allow, comment: 'Plex zeroconf' }
      - { port: 1900, rule: allow, comment: 'Plex dlna' }
      - { port: 8324, rule: allow, comment: 'Plex other' }
      - { port: 32469, rule: allow, comment: 'Plex other' }
      - { port: 32410, rule: allow, comment: 'Plex GDM network discover' }
      - { port: 32412, rule: allow, comment: 'Plex GDM network discover' }
      - { port: 32413, rule: allow, comment: 'Plex GDM network discover' }
      - { port: 32414, rule: allow, comment: 'Plex GDM network discover' }
      - { port: 51413, rule: allow, comment: 'Transmission' }
      - { port: 25565, rule: allow, comment: 'Minecraft' }
      - { port: 28016, rule: allow, comment: 'Minecraft' }
      - { port: 4326, rule: allow, comment: 'Minecraft' }
      - { port: 4327, rule: allow, comment: 'Minecraft' }
