# Quality of life basics
- hosts: adloquium
  become: yes
  handlers:
    - name: reload sysctl
      become: yes
      command: sysctl -p
  tasks:
    - apt:
        name: tree
    - apt:
        name: htop
    - apt:
        name: aptitude # cause if I see one more warning about this...
    - apt:
        name: mc
    - apt:
        name: zsh
    - apt:
        name: golang
    - apt:
        name: avahi-daemon
    - apt:
        name: postgresql-client
    - apt:
        name: zip
    - apt:
        name: python-pip
    - apt:
        name: influxdb-client
    - pip:
        name: awscli
    - service:
        name: avahi-daemon
        state: restarted
        enabled: yes
    - name: Set fswatchers
      lineinfile:
        path: /etc/sysctl.conf
        line: fs.inotify.max_user_watches=524288
        insertbefore: EOF
      notify: reload sysctl
