# Quality of life basics
- hosts: adloquium
  become: yes
  tasks:
    - apt:
        name: samba
    - name: Create /etc/samba/smb.conf
      template:
        src: ../templates/etc/samba/smb.conf.j2
        dest: /etc/samba/smb.conf
    - service:
        name: smbd
        state: restarted
        enabled: yes
