- alias: "Movie mode on"
  trigger:
  - entity_id: media_player.purgatory
    platform: state
    to: playing
    for: '00:00:05'
  condition:
  - condition: state
    entity_id: light.hue_ambiance_lamp_1
    state: 'on'
  - condition: state
    entity_id: light.hue_ambiance_lamp_3
    state: 'on'
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: "Living room"
      scene_name: "Movie"
- alias: "Movie mode off"
  trigger:
  - entity_id: media_player.purgatory
    platform: state
    from: playing
    to: paused
    for: '00:00:05'
  - entity_id: media_player.purgatory
    platform: state
    from: playing
    to: idle
    for: '00:00:05'
  condition:
  - condition: state
    entity_id: light.hue_ambiance_lamp_1
    state: 'on'
  - condition: state
    entity_id: light.hue_ambiance_lamp_3
    state: 'on'
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: "Living room"
      scene_name: "Czytanie"
