# - platform: rest
#   name: Uniwersytet Pedagogiczny departures
#   resource: https://mpk.jacekk.net/proxy_bus.php/services/passageInfo/stopPassages/stop?stop=88&mode=departure
#   force_update: true
#   json_attributes:
#     - actual
#   value_template: '{{ value_json["actual"][0] }}'

- platform: command_line
  name: Uniwersytet Pedagogiczny departures
  command: >
    curl -s \"https://mpk.jacekk.net/proxy_bus.php/services/passageInfo/stopPassages/stop?stop=88&mode=departure\" | jq \'[.actual | map(select(.direction == \"Stary Kleparz\")) | .[0:5] | .[] | { at: (.actualTime // .plannedTime), l: .patternText }]\'
  scan_interval: 60

- platform: command_line
  name: Bialucha departures
  command: >
    curl -s \"https://mpk.jacekk.net/proxy_tram.php/services/passageInfo/stopPassages/stop?stop=130&mode=departure\" | jq \'[.actual | map(select(.direction == \"Nowy Bieżanów P+R\")) |  map(select(.patternText == \"73\")) | .[0:5] | .[] | { at: (.actualTime // .plannedTime), l: .patternText }]\'
  scan_interval: 60
