# Main provisioning playbook

# Variable inclusion
- hosts: all
  become: yes
  tasks:
    - name: include vars from vars.yml
      include_vars:
        file: vars.yml

# Initialize Jarvis environment
- hosts: adloquium
  become: yes
  tasks:
    - name: Set JARVIS_DIR
      lineinfile:
        path: /etc/environment
        line: "JARVIS_DIR={{ jarvis_dir }}"
        insertbefore: EOF
    - name: Set GOPATH
      lineinfile:
        path: /etc/environment
        line: "GOPATH={{ jarvis_dir }}/.go"
        insertbefore: EOF
    - name: Create symbolic link for bin/jarvis
      become: yes
      file:
        src: "/jarvis/bin/jarvis"
        dest: "/usr/bin/jarvis"
        state: link

# - name: Quality of life stuff
#   import_playbook: plays/playbook.packages.yml

# - name: NVidia/docker/nvtop
#   import_playbook: plays/playbook.nvidia.yml

# - name: Docker services
#   import_playbook: plays/playbook.dockersrv.yml

- name: nginx
  import_playbook: plays/playbook.nginx.yml

- name: crontab
  import_playbook: plays/playbook.cron.yml
