# Main provisioning playbook

# Variable inclusion
- hosts: all
  become: yes
  tasks:
    - name: include vars from vars.yml
      include_vars:
        file: vars.yml

# Environment variables (persistent)
- hosts: adloquium
  become: yes
  tasks:
    - name: Set JARVIS_DIR
      lineinfile:
        path: /etc/environment
        line: "JARVIS_DIR={{ jarvis_dir }}"
        insertbefore: EOF

- name: Quality of life stuff
  import_playbook: plays/playbook.packages.yml

- name: NVidia/docker/nvtop
  import_playbook: plays/playbook.nvidia.yml

# Enable Jarvis binary systemwide
- hosts: adloquium
  become: yes
  tasks:
    - name: Create symbolic link for bin/smart-hose
      become: yes
      file:
        src: "/jarvis/bin/jarvis"
        dest: "/usr/bin/jarvis"
        state: link

- name: Docker services
  import_playbook: plays/playbook.dockersrv.yml
