- alias: Notify me that Radiance left
  trigger:
    - platform: state
      entity_id: person.magda
      to: 'not_home'
      for: '00:05:00'
  action:
    - service: notify.pjw_telegram
      data:
        message: 'Radiance is on the move.'

- alias: Notify me that Radiance came back
  trigger:
    - platform: state
      entity_id: person.magda
      to: 'home'
      for: '00:05:00'
  action:
    - service: notify.pjw_telegram
      data:
        message: 'Radiance is back at home base.'
